{{- if and .Values.certManager.enabled .Values.certManager.issuer.cloudflare.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certManager.issuer.cloudflare.apiTokenSecretRef.name }}
  namespace: {{ .Values.certManager.namespace | default "cert-manager" }}
  labels:
    {{- include "atelier.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.certManager.issuer.cloudflare.apiTokenSecretRef.key }}: {{ .Values.certManager.issuer.cloudflare.apiToken | b64enc | quote }}
{{- end }}
