apiVersion: v1
kind: Service
metadata:
  name: {{ include "atelier.fullname" . }}-manager
  namespace: {{ include "atelier.systemNamespace" . }}
  labels:
    {{- include "atelier.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  type: ClusterIP
  selector:
    {{- include "atelier.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: api
      port: {{ .Values.server.port }}
      targetPort: api
