apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "atelier.fullname" . }}-manager-data
  namespace: {{ include "atelier.systemNamespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "atelier.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.manager.persistence.storageClass }}
  storageClassName: {{ .Values.manager.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.manager.persistence.size }}
