apiVersion: v1
kind: Service
metadata:
  name: {{ include "atelier.fullname" . }}-manager
  namespace: {{ include "atelier.systemNamespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "atelier.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "atelier.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: manager
  ports:
    - name: http
      port: 8080
      targetPort: http
