apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "atelier.sandboxNamespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "atelier.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    atelier.dev/type: sandbox
