apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atelier.fullname" . }}-registries
  namespace: {{ include "atelier.systemNamespace" . }}
  labels:
    {{- include "atelier.labels" . | nindent 4 }}
data:
  registries.yaml: |
    {{- $registry := include "atelier.registryUrl" . }}
    {{- if $registry }}
    mirrors:
      "{{ $registry }}":
        endpoint:
          - "http://{{ $registry }}"
    {{- end }}
