{{- if .Values.verdaccio.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atelier.fullname" . }}-verdaccio-config
  namespace: {{ include "atelier.systemNamespace" . }}
  labels:
    {{- include "atelier.labels" . | nindent 4 }}
    app.kubernetes.io/component: verdaccio
data:
  config.yaml: |
    storage: /verdaccio/storage/packages

    auth:
      htpasswd:
        file: /verdaccio/storage/htpasswd
        max_users: 1000

    uplinks:
      npmjs:
        url: {{ .Values.verdaccio.uplink.url | quote }}
        cache: true
        maxage: {{ .Values.verdaccio.uplink.maxage | quote }}
        fail_timeout: {{ .Values.verdaccio.uplink.failTimeout | quote }}
        timeout: {{ .Values.verdaccio.uplink.timeout | quote }}
        max_fails: {{ .Values.verdaccio.uplink.maxFails }}
        agent_options:
          keepAlive: true
          maxSockets: 40

    packages:
      "@*/*":
        access: $all
        proxy: npmjs
      "**":
        access: $all
        proxy: npmjs

    server:
      keepAliveTimeout: 60

    listen: 0.0.0.0:{{ .Values.ports.verdaccio }}

    log:
      type: stdout
      format: pretty
      level: {{ .Values.verdaccio.log.level | quote }}

    max_body_size: {{ .Values.verdaccio.maxBodySize | quote }}
{{- end }}
