{{- if .Values.zot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atelier.fullname" . }}-zot
  namespace: {{ include "atelier.systemNamespace" . }}
  labels:
    {{- include "atelier.labels" . | nindent 4 }}
    app.kubernetes.io/component: zot
spec:
  type: ClusterIP
  selector:
    {{- include "atelier.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zot
  ports:
    - name: http
      port: {{ .Values.zot.port }}
      targetPort: http
{{- end }}
