name: Question
description: Ask a question about setup or usage
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you tried so far?
