/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SpawnRouteImport } from "./routes/spawn"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SandboxesSandboxIdRouteImport } from "./routes/sandboxes.$sandboxId"

const SpawnRoute = SpawnRouteImport.update({
  id: "/spawn",
  path: "/spawn",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesSandboxIdRoute = SandboxesSandboxIdRouteImport.update({
  id: "/sandboxes/$sandboxId",
  path: "/sandboxes/$sandboxId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/spawn": typeof SpawnRoute
  "/sandboxes/$sandboxId": typeof SandboxesSandboxIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/spawn": typeof SpawnRoute
  "/sandboxes/$sandboxId": typeof SandboxesSandboxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/spawn": typeof SpawnRoute
  "/sandboxes/$sandboxId": typeof SandboxesSandboxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/spawn" | "/sandboxes/$sandboxId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/spawn" | "/sandboxes/$sandboxId"
  id: "__root__" | "/" | "/spawn" | "/sandboxes/$sandboxId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpawnRoute: typeof SpawnRoute
  SandboxesSandboxIdRoute: typeof SandboxesSandboxIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/spawn": {
      id: "/spawn"
      path: "/spawn"
      fullPath: "/spawn"
      preLoaderRoute: typeof SpawnRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sandboxes/$sandboxId": {
      id: "/sandboxes/$sandboxId"
      path: "/sandboxes/$sandboxId"
      fullPath: "/sandboxes/$sandboxId"
      preLoaderRoute: typeof SandboxesSandboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpawnRoute: SpawnRoute,
  SandboxesSandboxIdRoute: SandboxesSandboxIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
