/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ImagesIndexRouteImport } from "./routes/images/index";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as IntegrationsIndexRouteImport } from "./routes/integrations/index";
import { Route as SandboxesIndexRouteImport } from "./routes/sandboxes/index";
import { Route as SettingsIndexRouteImport } from "./routes/settings/index";
import { Route as SystemIndexRouteImport } from "./routes/system/index";
import { Route as TasksIndexRouteImport } from "./routes/tasks/index";
import { Route as ThreadsIndexRouteImport } from "./routes/threads/index";
import { Route as WorkspacesIdRouteImport } from "./routes/workspaces/$id";
import { Route as WorkspacesIndexRouteImport } from "./routes/workspaces/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: "/workspaces/",
  path: "/workspaces/",
  getParentRoute: () => rootRouteImport,
} as any);
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: "/threads/",
  path: "/threads/",
  getParentRoute: () => rootRouteImport,
} as any);
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: "/tasks/",
  path: "/tasks/",
  getParentRoute: () => rootRouteImport,
} as any);
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: "/system/",
  path: "/system/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any);
const SandboxesIndexRoute = SandboxesIndexRouteImport.update({
  id: "/sandboxes/",
  path: "/sandboxes/",
  getParentRoute: () => rootRouteImport,
} as any);
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: "/integrations/",
  path: "/integrations/",
  getParentRoute: () => rootRouteImport,
} as any);
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: "/images/",
  path: "/images/",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspacesIdRoute = WorkspacesIdRouteImport.update({
  id: "/workspaces/$id",
  path: "/workspaces/$id",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/workspaces/$id": typeof WorkspacesIdRoute;
  "/images/": typeof ImagesIndexRoute;
  "/integrations/": typeof IntegrationsIndexRoute;
  "/sandboxes/": typeof SandboxesIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/system/": typeof SystemIndexRoute;
  "/tasks/": typeof TasksIndexRoute;
  "/threads/": typeof ThreadsIndexRoute;
  "/workspaces/": typeof WorkspacesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/workspaces/$id": typeof WorkspacesIdRoute;
  "/images": typeof ImagesIndexRoute;
  "/integrations": typeof IntegrationsIndexRoute;
  "/sandboxes": typeof SandboxesIndexRoute;
  "/settings": typeof SettingsIndexRoute;
  "/system": typeof SystemIndexRoute;
  "/tasks": typeof TasksIndexRoute;
  "/threads": typeof ThreadsIndexRoute;
  "/workspaces": typeof WorkspacesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/workspaces/$id": typeof WorkspacesIdRoute;
  "/images/": typeof ImagesIndexRoute;
  "/integrations/": typeof IntegrationsIndexRoute;
  "/sandboxes/": typeof SandboxesIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/system/": typeof SystemIndexRoute;
  "/tasks/": typeof TasksIndexRoute;
  "/threads/": typeof ThreadsIndexRoute;
  "/workspaces/": typeof WorkspacesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/workspaces/$id"
    | "/images/"
    | "/integrations/"
    | "/sandboxes/"
    | "/settings/"
    | "/system/"
    | "/tasks/"
    | "/threads/"
    | "/workspaces/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/workspaces/$id"
    | "/images"
    | "/integrations"
    | "/sandboxes"
    | "/settings"
    | "/system"
    | "/tasks"
    | "/threads"
    | "/workspaces";
  id:
    | "__root__"
    | "/"
    | "/workspaces/$id"
    | "/images/"
    | "/integrations/"
    | "/sandboxes/"
    | "/settings/"
    | "/system/"
    | "/tasks/"
    | "/threads/"
    | "/workspaces/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WorkspacesIdRoute: typeof WorkspacesIdRoute;
  ImagesIndexRoute: typeof ImagesIndexRoute;
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute;
  SandboxesIndexRoute: typeof SandboxesIndexRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
  SystemIndexRoute: typeof SystemIndexRoute;
  TasksIndexRoute: typeof TasksIndexRoute;
  ThreadsIndexRoute: typeof ThreadsIndexRoute;
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workspaces/": {
      id: "/workspaces/";
      path: "/workspaces";
      fullPath: "/workspaces/";
      preLoaderRoute: typeof WorkspacesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/threads/": {
      id: "/threads/";
      path: "/threads";
      fullPath: "/threads/";
      preLoaderRoute: typeof ThreadsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tasks/": {
      id: "/tasks/";
      path: "/tasks";
      fullPath: "/tasks/";
      preLoaderRoute: typeof TasksIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/system/": {
      id: "/system/";
      path: "/system";
      fullPath: "/system/";
      preLoaderRoute: typeof SystemIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sandboxes/": {
      id: "/sandboxes/";
      path: "/sandboxes";
      fullPath: "/sandboxes/";
      preLoaderRoute: typeof SandboxesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/integrations/": {
      id: "/integrations/";
      path: "/integrations";
      fullPath: "/integrations/";
      preLoaderRoute: typeof IntegrationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/images/": {
      id: "/images/";
      path: "/images";
      fullPath: "/images/";
      preLoaderRoute: typeof ImagesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workspaces/$id": {
      id: "/workspaces/$id";
      path: "/workspaces/$id";
      fullPath: "/workspaces/$id";
      preLoaderRoute: typeof WorkspacesIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspacesIdRoute: WorkspacesIdRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  SandboxesIndexRoute: SandboxesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
